url: 'https://blog.curiodyssee.com/'
baseurl: ''
title: 'Curiodyssée'
collections_dir: collections

logo:
  logo_desktop_image: assets/images/logo.jpeg
  logo_desktop_text: 'Curiodyssée'
  logo_mobile_image: assets/images/logo.jpeg
  logo_mobile_text: 'Curiodyssée'
  logo_desktop_height: '36px'
  logo_desktop_width: '36px'
  logo_mobile_height: '36px'
  logo_mobile_width: '36px'

seo:
  meta_og_image: 'assets/images/curiodyssee-blog.png'

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  posts:
    output: true
    permalink: /blog/:path/
  christmas:
    output: true
    permalink: /calendrier/:path/

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'categories'
    values:
      layout: category
      permalink: /category/:basename/
  - scope:
      path: ''
      type: christmas-post
    values:
      layout: christmas-post

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
