url: 'https://elisedjn.github.io'
baseurl: 'curiodyssee-blog'
title: 'Curiodyssée'
collections_dir: collections

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  posts:
    output: true
    permalink: /blog/:path/

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
