url: 'https://blog.curiodyssee.com/'
baseurl: ''
title: 'Curiodyssée'
collections_dir: collections

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'categories'
    values:
      layout: category
      permalink: /category/:basename/

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
