name: Daily publish

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d45d564b-daf1-4e3e-9bda-41b690b345bc'
        method: 'POST'
        # username: ${{ secrets.AWX_USER }}
        # password: ${{ secrets.AWX_PASSWORD }}
        # customHeaders: '{"Content-Type": "application/json"}'
        # data: '{"key_1": "value_1", "key_2": "value_2"}'

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       deployments: write
#     name: Publish to Cloudflare Pages
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       # Run a build step here if your project requires

#       - name: Publish to Cloudflare Pages
#         uses: cloudflare/pages-action@v1
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: 311be569ba1724aca62869cc5497e94e
#           projectName: /curiodyssee-blog
#           directory: _site
#           # Optional: Enable this if you want to have GitHub Deployments triggered
#           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
#           # Optional: Switch what branch you are publishing to.
#           # By default this will be the branch which triggered this workflow
#           branch: main
#           # Optional: Change the working directory
#           # workingDirectory: my-site
#           # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
#           wranglerVersion: '3'